[package]
name = "wcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapproj = "0.3.0"
enum_dispatch = "0.3.8"
fitsrs = { package = "fitsrs", git = 'https://github.com/cds-astro/fitsrs', branch = 'reader' }
quick-error = "2.0.1"
paste = "1.0.11"

[dev-dependencies]
image = "0.24.5"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
glob = "0.3.0"